language: python
python:
  - "3.6"

install: pip install -r requirements.txt
# command to run tests 
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start

before_script:
  - wget http://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.7/bin/  
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" 

addons:
  chrome: stable
script: python tests.py 