language: python
python:
  - "3.6"

install: pip install -r requirements.txt
# command to run tests 
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start

addons:
  chrome: stable
script: python tests.py 