language: python
python:
  - "3.6"
 
install: 
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests 

addons:
  chrome: stable
  
services:
  - xvfb

before_install:
  - wget http://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d drivers  
  
addons:
  chrome: stable
  
script: 
  - python testsbadge.py 
  - coverage run testsbadge.py    

after_success:
  - codecov 
